### ISSUE TITLE
knitting errors

### ISSUE THREAD

**Issue by jvcasillas** [ccy07/finalds4ling#2]
I had to make the path to your data relative in order to get your manuscript to knit. Here is an example of what that looks like: 

```
df_tidy<- read.csv("../Data_tidy_raw/data_tidy1.csv")
```

**Comment by jvcasillas** [comment]
This was also true for the slides.

**Comment by ccy07** [comment]
Hi Joseph! Thanks for your message and I have changed the path in the files. Hope they work now.
